// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Message.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_MESSAGE_MESSAGE_H_
#define _FAST_DDS_GENERATED_MESSAGE_MESSAGE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MESSAGE_SOURCE)
#define MESSAGE_DllAPI __declspec( dllexport )
#else
#define MESSAGE_DllAPI __declspec( dllimport )
#endif // MESSAGE_SOURCE
#else
#define MESSAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MESSAGE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima



namespace Message {



/*!
 * @brief This class represents the structure Request defined by the user in the IDL file.
 * @ingroup Message
 */
class Request
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Request();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Request();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Message::Request that will be copied.
     */
    eProsima_user_DllExport Request(
            const Request& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Message::Request that will be copied.
     */
    eProsima_user_DllExport Request(
            Request&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Message::Request that will be copied.
     */
    eProsima_user_DllExport Request& operator =(
            const Request& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Message::Request that will be copied.
     */
    eProsima_user_DllExport Request& operator =(
            Request&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Message::Request object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Request& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Message::Request object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Request& x) const;

    /*!
     * @brief This function sets a value in member stamp
     * @param _stamp New value for member stamp
     */
    eProsima_user_DllExport void stamp(
            uint64_t _stamp);

    /*!
     * @brief This function returns the value of member stamp
     * @return Value of member stamp
     */
    eProsima_user_DllExport uint64_t stamp() const;

    /*!
     * @brief This function returns a reference to member stamp
     * @return Reference to member stamp
     */
    eProsima_user_DllExport uint64_t& stamp();


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::array<char, 50>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::array<char, 50>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::array<char, 50>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::array<char, 50>& data();

private:

    uint64_t m_stamp{0};
    std::array<char, 50> m_data{0};

};


/*!
 * @brief This class represents the structure Pointcloud1200x800x4 defined by the user in the IDL file.
 * @ingroup Message
 */
class Pointcloud1200x800x4
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Pointcloud1200x800x4();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Pointcloud1200x800x4();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Message::Pointcloud1200x800x4 that will be copied.
     */
    eProsima_user_DllExport Pointcloud1200x800x4(
            const Pointcloud1200x800x4& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Message::Pointcloud1200x800x4 that will be copied.
     */
    eProsima_user_DllExport Pointcloud1200x800x4(
            Pointcloud1200x800x4&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Message::Pointcloud1200x800x4 that will be copied.
     */
    eProsima_user_DllExport Pointcloud1200x800x4& operator =(
            const Pointcloud1200x800x4& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Message::Pointcloud1200x800x4 that will be copied.
     */
    eProsima_user_DllExport Pointcloud1200x800x4& operator =(
            Pointcloud1200x800x4&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Message::Pointcloud1200x800x4 object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Pointcloud1200x800x4& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Message::Pointcloud1200x800x4 object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Pointcloud1200x800x4& x) const;

    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const std::array<char, 50>& _frame_id);

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            std::array<char, 50>&& _frame_id);

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const std::array<char, 50>& frame_id() const;

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport std::array<char, 50>& frame_id();


    /*!
     * @brief This function sets a value in member stamp
     * @param _stamp New value for member stamp
     */
    eProsima_user_DllExport void stamp(
            uint64_t _stamp);

    /*!
     * @brief This function returns the value of member stamp
     * @return Value of member stamp
     */
    eProsima_user_DllExport uint64_t stamp() const;

    /*!
     * @brief This function returns a reference to member stamp
     * @return Reference to member stamp
     */
    eProsima_user_DllExport uint64_t& stamp();


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint32_t _height);

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint32_t height() const;

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint32_t& height();


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint32_t _width);

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint32_t width() const;

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint32_t& width();


    /*!
     * @brief This function sets a value in member channel
     * @param _channel New value for member channel
     */
    eProsima_user_DllExport void channel(
            uint32_t _channel);

    /*!
     * @brief This function returns the value of member channel
     * @return Value of member channel
     */
    eProsima_user_DllExport uint32_t channel() const;

    /*!
     * @brief This function returns a reference to member channel
     * @return Reference to member channel
     */
    eProsima_user_DllExport uint32_t& channel();


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::array<float, 1200*800*4>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::array<float, 1200*800*4>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::array<float, 1200*800*4>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::array<float, 1200*800*4>& data();

private:

    std::array<char, 50> m_frame_id{0};
    uint64_t m_stamp{0};
    uint32_t m_height{0};
    uint32_t m_width{0};
    uint32_t m_channel{0};
    std::array<float, 1200*800*4> m_data{0.0};

};


/*!
 * @brief This class represents the structure Pointcloud1920x1080x3 defined by the user in the IDL file.
 * @ingroup Message
 */
class Pointcloud1920x1080x3
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Pointcloud1920x1080x3();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Pointcloud1920x1080x3();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Message::Pointcloud1920x1080x3 that will be copied.
     */
    eProsima_user_DllExport Pointcloud1920x1080x3(
            const Pointcloud1920x1080x3& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Message::Pointcloud1920x1080x3 that will be copied.
     */
    eProsima_user_DllExport Pointcloud1920x1080x3(
            Pointcloud1920x1080x3&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Message::Pointcloud1920x1080x3 that will be copied.
     */
    eProsima_user_DllExport Pointcloud1920x1080x3& operator =(
            const Pointcloud1920x1080x3& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Message::Pointcloud1920x1080x3 that will be copied.
     */
    eProsima_user_DllExport Pointcloud1920x1080x3& operator =(
            Pointcloud1920x1080x3&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Message::Pointcloud1920x1080x3 object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Pointcloud1920x1080x3& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Message::Pointcloud1920x1080x3 object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Pointcloud1920x1080x3& x) const;

    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const std::array<char, 50>& _frame_id);

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            std::array<char, 50>&& _frame_id);

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const std::array<char, 50>& frame_id() const;

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport std::array<char, 50>& frame_id();


    /*!
     * @brief This function sets a value in member stamp
     * @param _stamp New value for member stamp
     */
    eProsima_user_DllExport void stamp(
            uint64_t _stamp);

    /*!
     * @brief This function returns the value of member stamp
     * @return Value of member stamp
     */
    eProsima_user_DllExport uint64_t stamp() const;

    /*!
     * @brief This function returns a reference to member stamp
     * @return Reference to member stamp
     */
    eProsima_user_DllExport uint64_t& stamp();


    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint32_t _height);

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint32_t height() const;

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint32_t& height();


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint32_t _width);

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint32_t width() const;

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint32_t& width();


    /*!
     * @brief This function sets a value in member channel
     * @param _channel New value for member channel
     */
    eProsima_user_DllExport void channel(
            uint32_t _channel);

    /*!
     * @brief This function returns the value of member channel
     * @return Value of member channel
     */
    eProsima_user_DllExport uint32_t channel() const;

    /*!
     * @brief This function returns a reference to member channel
     * @return Reference to member channel
     */
    eProsima_user_DllExport uint32_t& channel();


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::array<float, 1920*1080*3>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::array<float, 1920*1080*3>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::array<float, 1920*1080*3>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::array<float, 1920*1080*3>& data();

private:

    std::array<char, 50> m_frame_id{0};
    uint64_t m_stamp{0};
    uint32_t m_height{0};
    uint32_t m_width{0};
    uint32_t m_channel{0};
    std::array<float, 1920*1080*3> m_data{0.0};

};


/*!
 * @brief This class represents the structure Laserscan1500 defined by the user in the IDL file.
 * @ingroup Message
 */
class Laserscan1500
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Laserscan1500();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Laserscan1500();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Message::Laserscan1500 that will be copied.
     */
    eProsima_user_DllExport Laserscan1500(
            const Laserscan1500& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Message::Laserscan1500 that will be copied.
     */
    eProsima_user_DllExport Laserscan1500(
            Laserscan1500&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Message::Laserscan1500 that will be copied.
     */
    eProsima_user_DllExport Laserscan1500& operator =(
            const Laserscan1500& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Message::Laserscan1500 that will be copied.
     */
    eProsima_user_DllExport Laserscan1500& operator =(
            Laserscan1500&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Message::Laserscan1500 object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Laserscan1500& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Message::Laserscan1500 object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Laserscan1500& x) const;

    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const std::array<char, 50>& _frame_id);

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            std::array<char, 50>&& _frame_id);

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const std::array<char, 50>& frame_id() const;

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport std::array<char, 50>& frame_id();


    /*!
     * @brief This function sets a value in member stamp
     * @param _stamp New value for member stamp
     */
    eProsima_user_DllExport void stamp(
            uint64_t _stamp);

    /*!
     * @brief This function returns the value of member stamp
     * @return Value of member stamp
     */
    eProsima_user_DllExport uint64_t stamp() const;

    /*!
     * @brief This function returns a reference to member stamp
     * @return Reference to member stamp
     */
    eProsima_user_DllExport uint64_t& stamp();


    /*!
     * @brief This function sets a value in member range_min
     * @param _range_min New value for member range_min
     */
    eProsima_user_DllExport void range_min(
            float _range_min);

    /*!
     * @brief This function returns the value of member range_min
     * @return Value of member range_min
     */
    eProsima_user_DllExport float range_min() const;

    /*!
     * @brief This function returns a reference to member range_min
     * @return Reference to member range_min
     */
    eProsima_user_DllExport float& range_min();


    /*!
     * @brief This function sets a value in member range_max
     * @param _range_max New value for member range_max
     */
    eProsima_user_DllExport void range_max(
            float _range_max);

    /*!
     * @brief This function returns the value of member range_max
     * @return Value of member range_max
     */
    eProsima_user_DllExport float range_max() const;

    /*!
     * @brief This function returns a reference to member range_max
     * @return Reference to member range_max
     */
    eProsima_user_DllExport float& range_max();


    /*!
     * @brief This function sets a value in member angle_min
     * @param _angle_min New value for member angle_min
     */
    eProsima_user_DllExport void angle_min(
            float _angle_min);

    /*!
     * @brief This function returns the value of member angle_min
     * @return Value of member angle_min
     */
    eProsima_user_DllExport float angle_min() const;

    /*!
     * @brief This function returns a reference to member angle_min
     * @return Reference to member angle_min
     */
    eProsima_user_DllExport float& angle_min();


    /*!
     * @brief This function sets a value in member angle_max
     * @param _angle_max New value for member angle_max
     */
    eProsima_user_DllExport void angle_max(
            float _angle_max);

    /*!
     * @brief This function returns the value of member angle_max
     * @return Value of member angle_max
     */
    eProsima_user_DllExport float angle_max() const;

    /*!
     * @brief This function returns a reference to member angle_max
     * @return Reference to member angle_max
     */
    eProsima_user_DllExport float& angle_max();


    /*!
     * @brief This function sets a value in member angle_increment
     * @param _angle_increment New value for member angle_increment
     */
    eProsima_user_DllExport void angle_increment(
            float _angle_increment);

    /*!
     * @brief This function returns the value of member angle_increment
     * @return Value of member angle_increment
     */
    eProsima_user_DllExport float angle_increment() const;

    /*!
     * @brief This function returns a reference to member angle_increment
     * @return Reference to member angle_increment
     */
    eProsima_user_DllExport float& angle_increment();


    /*!
     * @brief This function sets a value in member ranges_size
     * @param _ranges_size New value for member ranges_size
     */
    eProsima_user_DllExport void ranges_size(
            uint32_t _ranges_size);

    /*!
     * @brief This function returns the value of member ranges_size
     * @return Value of member ranges_size
     */
    eProsima_user_DllExport uint32_t ranges_size() const;

    /*!
     * @brief This function returns a reference to member ranges_size
     * @return Reference to member ranges_size
     */
    eProsima_user_DllExport uint32_t& ranges_size();


    /*!
     * @brief This function copies the value in member ranges
     * @param _ranges New value to be copied in member ranges
     */
    eProsima_user_DllExport void ranges(
            const std::array<float, 1500>& _ranges);

    /*!
     * @brief This function moves the value in member ranges
     * @param _ranges New value to be moved in member ranges
     */
    eProsima_user_DllExport void ranges(
            std::array<float, 1500>&& _ranges);

    /*!
     * @brief This function returns a constant reference to member ranges
     * @return Constant reference to member ranges
     */
    eProsima_user_DllExport const std::array<float, 1500>& ranges() const;

    /*!
     * @brief This function returns a reference to member ranges
     * @return Reference to member ranges
     */
    eProsima_user_DllExport std::array<float, 1500>& ranges();


    /*!
     * @brief This function copies the value in member intensities
     * @param _intensities New value to be copied in member intensities
     */
    eProsima_user_DllExport void intensities(
            const std::array<float, 1500>& _intensities);

    /*!
     * @brief This function moves the value in member intensities
     * @param _intensities New value to be moved in member intensities
     */
    eProsima_user_DllExport void intensities(
            std::array<float, 1500>&& _intensities);

    /*!
     * @brief This function returns a constant reference to member intensities
     * @return Constant reference to member intensities
     */
    eProsima_user_DllExport const std::array<float, 1500>& intensities() const;

    /*!
     * @brief This function returns a reference to member intensities
     * @return Reference to member intensities
     */
    eProsima_user_DllExport std::array<float, 1500>& intensities();

private:

    std::array<char, 50> m_frame_id{0};
    uint64_t m_stamp{0};
    float m_range_min{0.0};
    float m_range_max{0.0};
    float m_angle_min{0.0};
    float m_angle_max{0.0};
    float m_angle_increment{0.0};
    uint32_t m_ranges_size{0};
    std::array<float, 1500> m_ranges{0.0};
    std::array<float, 1500> m_intensities{0.0};

};


/*!
 * @brief This class represents the structure Scalar defined by the user in the IDL file.
 * @ingroup Message
 */
class Scalar
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Scalar();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Scalar();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Message::Scalar that will be copied.
     */
    eProsima_user_DllExport Scalar(
            const Scalar& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Message::Scalar that will be copied.
     */
    eProsima_user_DllExport Scalar(
            Scalar&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Message::Scalar that will be copied.
     */
    eProsima_user_DllExport Scalar& operator =(
            const Scalar& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Message::Scalar that will be copied.
     */
    eProsima_user_DllExport Scalar& operator =(
            Scalar&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Message::Scalar object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Scalar& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Message::Scalar object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Scalar& x) const;

    /*!
     * @brief This function sets a value in member stamp
     * @param _stamp New value for member stamp
     */
    eProsima_user_DllExport void stamp(
            uint64_t _stamp);

    /*!
     * @brief This function returns the value of member stamp
     * @return Value of member stamp
     */
    eProsima_user_DllExport uint64_t stamp() const;

    /*!
     * @brief This function returns a reference to member stamp
     * @return Reference to member stamp
     */
    eProsima_user_DllExport uint64_t& stamp();


    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::array<char, 50>& _name);

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::array<char, 50>&& _name);

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::array<char, 50>& name() const;

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::array<char, 50>& name();


    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(
            float _value);

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport float value() const;

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport float& value();

private:

    uint64_t m_stamp{0};
    std::array<char, 50> m_name{0};
    float m_value{0.0};

};


/*!
 * @brief This class represents the structure ScalarList20 defined by the user in the IDL file.
 * @ingroup Message
 */
class ScalarList20
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ScalarList20();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ScalarList20();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Message::ScalarList20 that will be copied.
     */
    eProsima_user_DllExport ScalarList20(
            const ScalarList20& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Message::ScalarList20 that will be copied.
     */
    eProsima_user_DllExport ScalarList20(
            ScalarList20&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Message::ScalarList20 that will be copied.
     */
    eProsima_user_DllExport ScalarList20& operator =(
            const ScalarList20& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Message::ScalarList20 that will be copied.
     */
    eProsima_user_DllExport ScalarList20& operator =(
            ScalarList20&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Message::ScalarList20 object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ScalarList20& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Message::ScalarList20 object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ScalarList20& x) const;

    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::array<Message::Scalar, 20>& _data);

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::array<Message::Scalar, 20>&& _data);

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::array<Message::Scalar, 20>& data() const;

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::array<Message::Scalar, 20>& data();

private:

    std::array<Message::Scalar, 20> m_data;

};

} // namespace Message

#endif // _FAST_DDS_GENERATED_MESSAGE_MESSAGE_H_



