// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MessageCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_MESSAGE_MESSAGECDRAUX_HPP_
#define _FAST_DDS_GENERATED_MESSAGE_MESSAGECDRAUX_HPP_

#include "Message.h"

constexpr uint32_t Message_Request_max_cdr_typesize {58UL};
constexpr uint32_t Message_Request_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_PointD_max_cdr_typesize {24UL};
constexpr uint32_t Message_PointD_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_ScalarList20_max_cdr_typesize {1288UL};
constexpr uint32_t Message_ScalarList20_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_Laserscan1500_max_cdr_typesize {12088UL};
constexpr uint32_t Message_Laserscan1500_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_QuaternionD_max_cdr_typesize {32UL};
constexpr uint32_t Message_QuaternionD_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_PoseStamped_max_cdr_typesize {112UL};
constexpr uint32_t Message_PoseStamped_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_Pointcloud1200x800x4_max_cdr_typesize {15360076UL};
constexpr uint32_t Message_Pointcloud1200x800x4_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_Pointcloud1920x1080x3_max_cdr_typesize {24883276UL};
constexpr uint32_t Message_Pointcloud1920x1080x3_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_HeaderString1024_max_cdr_typesize {1092UL};
constexpr uint32_t Message_HeaderString1024_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_Pointcloud640x480x3_max_cdr_typesize {3686476UL};
constexpr uint32_t Message_Pointcloud640x480x3_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_Scalar_max_cdr_typesize {64UL};
constexpr uint32_t Message_Scalar_max_key_cdr_typesize {0UL};

constexpr uint32_t Message_Path1024_max_cdr_typesize {114756UL};
constexpr uint32_t Message_Path1024_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::Request& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::Pointcloud1200x800x4& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::Pointcloud640x480x3& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::Pointcloud1920x1080x3& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::Laserscan1500& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::Scalar& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::ScalarList20& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::HeaderString1024& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::PointD& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::QuaternionD& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::PoseStamped& data);



eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const Message::Path1024& data);



} // namespace fastcdr
} // namespace eprosima

#endif // _FAST_DDS_GENERATED_MESSAGE_MESSAGECDRAUX_HPP_

