

[dds.participant]
xml = "dds_config.xml"
profile = "participant_discovery_protocol_SIMPLE"
name = "dds_ros_bridge_0"
#interface_allowlist = []
#interface_blocklist = []
interface_allowlist = ["lo"]
interface_blocklist = ["eno1", "enx00e04d71ffe7", "wlp4s0", "wlp3s0", "docker0", "wt0"]

#[dds.readers]


[dds.writers.cloud_pub]
topic_name = "pallet_detector/cloud"
topic_type = "Message::Pointcloud640x480x3"
#topic_type = "Message::Pointcloud1920x1080x3"

pub_profile = ""
topic_profile = ""
writer_profile = ""
qos_queue_size = 1

#
[dds.writers.detector_cmd_pub]
topic_name = "pallet_detector/cmd"
topic_type = "Message::HeaderString1024"
#topic_type = "Message::Pointcloud1920x1080x3"

pub_profile = ""
topic_profile = ""
writer_profile = ""
qos_queue_size = 10



[dds.readers.detector_status_sub]
topic_name = "pallet_detector/status"
topic_type = "Message::HeaderString1024"
#topic_type = "Message::Pointcloud1920x1080x3"

sub_profile = ""
topic_profile = ""
reader_profile = ""
qos_queue_size = 100

[dds.readers.detector_result_sub]
topic_name = "pallet_detector/result"
topic_type = "Message::Path1024"
#topic_type = "Message::Pointcloud1920x1080x3"

sub_profile = ""
topic_profile = ""
reader_profile = ""
qos_queue_size = 100