# This is a TOML document.

[general]
version = 1


# http://wiki.ros.org/Remapping%20Arguments
# config parameter will be passed to ros init function
[ros.config]
__name = "dds_ros_bridge_2"

#[ros.writers]

[ros.readers.cloud_sub]
#topic_name = "velodyne_points"
topic_name = "camera/depth/points"
topic_type = "PointCloud2"
qos_queue_size = 1


[ros.readers.detector_cmd_sub]
#topic_name = "velodyne_points"
topic_name = "pallet_detector/cmd"
topic_type = "HeaderString"
qos_queue_size = 1

[ros.writers.detector_status_pub]
#topic_name = "velodyne_points"
topic_name = "pallet_detector/status"
topic_type = "HeaderString"
qos_queue_size = 1


[ros.writers.detector_result_pub]
#topic_name = "velodyne_points"
topic_name = "pallet_detector/result"
topic_type = "Path"
qos_queue_size = 1
