

[dds.participant]
xml = "gui_config.xml"
profile = "participant_discovery_protocol_SIMPLE"
name = "dds_test_1"
#interface_allowlist = []
#interface_blocklist = []
interface_allowlist = ["lo"]
interface_blocklist = ["eno1", "enx00e04d71ffe7", "wlp4s0", "wlp3s0", "docker0", "wt0"]

[dds.readers.cloud_sub]
topic_name = "cloud"
topic_type = "Message::Pointcloud640x480x3"
sub_profile = ""
topic_profile = ""
reader_profile = "shm_reader_profile"
qos_queue_size = 2

#[dds.writers.cloud_pub]
#topic_name = "cloud2"
#topic_type = "Message::Pointcloud1920x1080x3"
#pub_profile = ""
#topic_profile = ""
#writer_profile = ""
#qos_queue_size = 1

[dds.writers]


# 1.57079632679489661923132169163975144
#3.14159265358979323846264338327950288
[gui.extrinsic.pose]
tx = 0.4
ty = 0.0
tz = 0.5
roll = 0.0
pitch = 0.0
yaw = 0.0
[gui.extrinsic]
enable = true

[gui.cloud.dim]
height = 480
width = 640
[gui.cloud.filter]
filter_height_min = 0
filter_height_max = 480
filter_width_min = 0
filter_width_max = 640
filter_x_min = 0.0
filter_x_max = 0.0
filter_y_min = 0.0
filter_y_max = 0.0
filter_z_min = 0.0
filter_z_max = 0.0

